#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

DOTS=".dots"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/${DOTS:-".zprezto"}/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/${DOTS:-".zprezto"}/init.zsh"
fi

# Customize to your needs...
VISUAL="vim"
EDITOR="vim"

# load system specific config (if it exists)
if [[ -f ~/.profile ]]
then
    source ~/.profile
fi

# if a MOTD exists, use it
if [[ -f ~/.motd ]]; 
then
    cat ~/.motd
fi
