#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

DOTS=".dots"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/${DOTS:-".zprezto"}/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/${DOTS:-".zprezto"}/init.zsh"
fi

# Customize to your needs...
VISUAL="vim"
EDITOR="vim"

PATH="$PATH:/home/zac/.gem/ruby/2.2.0/bin"
