filetype off
set rtp+=~/.vim/bundle/Vundle.vim

"" vundle configuration

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'bling/vim-airline'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-git'
Bundle 'sheerun/vim-polyglot'
Bundle 'altercation/vim-colors-solarized'
call vundle#end()            " required
filetype plugin indent on

"" general configuration

set nocompatible
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set showcmd
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set backspace=2
set autoindent
set formatoptions=c,q,r,t
set ruler
set background=dark
set laststatus=2

"" split behaviour changes
set splitbelow
set splitright

"" final stuff

filetype plugin indent on
syntax on
set background=dark
colorscheme solarized

"" special config options
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
