filetype off
set rtp+=~/.vim/bundle/Vundle.vim

"" vundle configuration

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'bling/vim-airline'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-git'
Bundle 'sheerun/vim-polyglot'
Bundle 'altercation/vim-colors-solarized'
Plugin 'chriskempson/base16-vim'
Bundle 'ervandew/supertab'
Bundle 'vim-scripts/pep8'
Bundle 'edthedev/minion'
call vundle#end()            " required
filetype plugin indent on

"" general configuration

set nocompatible
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set showcmd
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set backspace=2
set autoindent
set formatoptions=c,q,r,t
set ruler
set laststatus=2
set foldmethod=indent
set foldlevel=99
set noshowmode

au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview

"" split behaviour changes
set splitbelow
set splitright

"" final stuff

filetype plugin indent on
syntax on
let base16colorspace=256
"" colorscheme base16-atelierdune
"" set background=dark
colorscheme base16-apathy 

"" special config options
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" special keymapping
nnoremap <silent> <F9> :!clear;!./% <CR>
